# This is the only configuration needed for a production environment like Render.
# It directly tells Rails to use the DATABASE_URL environment variable.
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
