# This is the standard Rails database configuration file.
# The production database is configured below to use the DATABASE_URL environment variable.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chatbot_backend_development

test:
  <<: *default
  database: chatbot_backend_test

# On Render, the DATABASE_URL environment variable is automatically provided
# for your service. This is the only configuration needed for production.
production:
  url: <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
